services:
  companion:
    image: ghcr.io/bitfocus/companion/companion:3.5.0-7659-main-0f3d0de7
    container_name: bitfocus-companion
    restart: on-failure
    ports:
      - "8000:8000"
      - "16622:16622"
      - "16623:16623"
      - "28492:28492"
      - "5343:5343"
    volumes:
      - ${APP_DATA_DIR}:/companion

